# Generated by Django 5.1.2 on 2024-10-17 11:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('latitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-90, 'Latitude must be greater than -90.'), django.core.validators.MaxValueValidator(90, 'Latitude must be less than 90.')])),
                ('longitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-180, 'Longitude must be greater than -180.'), django.core.validators.MaxValueValidator(180, 'Longitude must be less than 180.')])),
            ],
        ),
    ]
